[project]
name = "human-eval"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "rapidata>=2.27.0",
    "wandb>=0.20.0",
]

[tool.uv.workspace]
members = ["human-eval"]
